//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace untitled_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class productDetail
    {
        public int ID { get; set; }
        public string name { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> marketPrice { get; set; }
        public Nullable<int> size { get; set; }
        public string color { get; set; }
        public Nullable<int> stock { get; set; }
        public string maintag { get; set; }
        public string tag1 { get; set; }
        public string tag2 { get; set; }
        public string tag3 { get; set; }
        public string tag4 { get; set; }
        public string tag5 { get; set; }
        public string tag6 { get; set; }
        public string tag7 { get; set; }
        public string productDescription { get; set; }
    }
}
