//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace untitled_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class productImage
    {
        public int pID { get; set; }
        public byte[] mainImg { get; set; }
        public byte[] ima1 { get; set; }
        public byte[] img2 { get; set; }
        public byte[] img3 { get; set; }
        public byte[] img4 { get; set; }
        public byte[] img5 { get; set; }
    }
}
